radio.onReceivedNumber(function (receivedNumber) {
    if (receivedNumber == 1) {
        Vocal_L0()
        Vocal_L1()
        Vocal_L2()
        Vocal_L3()
        Vocal_L4()
        Vocal_L5()
        Vocal_L6()
    }
})
function Vocal_L6 () {
    music.playTone(466, music.beat(BeatFraction.Whole))
    music.playTone(554, music.beat(BeatFraction.Whole))
    music.playTone(698, music.beat(BeatFraction.Whole))
    music.playTone(622, music.beat(BeatFraction.Double))
    music.rest(music.beat(BeatFraction.Whole))
    music.playTone(523, music.beat(BeatFraction.Whole))
    music.playTone(622, music.beat(BeatFraction.Whole))
    music.playTone(587, music.beat(BeatFraction.Whole))
    music.playTone(554, music.beat(BeatFraction.Whole) * 1.5)
    music.playTone(392, music.beat(BeatFraction.Half))
    music.playTone(415, music.beat(BeatFraction.Breve))
    music.rest(music.beat(BeatFraction.Whole))
}
input.onButtonPressed(Button.A, function () {
    radio.sendNumber(1)
    Vocal_L0()
    Vocal_L1()
    Vocal_L2()
    Vocal_L3()
    Vocal_L4()
    Vocal_L5()
    Vocal_L6()
})
function Vocal_L4 () {
    music.playTone(466, music.beat(BeatFraction.Whole))
    music.playTone(554, music.beat(BeatFraction.Whole))
    music.playTone(698, music.beat(BeatFraction.Whole))
    music.playTone(622, music.beat(BeatFraction.Double))
    music.rest(music.beat(BeatFraction.Whole))
    music.playTone(523, music.beat(BeatFraction.Whole))
    music.playTone(622, music.beat(BeatFraction.Whole))
    music.playTone(587, music.beat(BeatFraction.Whole))
    music.playTone(554, music.beat(BeatFraction.Whole) * 1.5)
    music.playTone(466, music.beat(BeatFraction.Half))
    music.playTone(523, music.beat(BeatFraction.Breve))
    music.rest(music.beat(BeatFraction.Whole))
}
function Vocal_L5 () {
    music.playTone(311, music.beat(BeatFraction.Whole))
    music.playTone(415, music.beat(BeatFraction.Whole))
    music.playTone(523, music.beat(BeatFraction.Whole))
    music.playTone(622, music.beat(BeatFraction.Double))
    music.rest(music.beat(BeatFraction.Whole))
    music.playTone(523, music.beat(BeatFraction.Whole))
    music.playTone(554, music.beat(BeatFraction.Whole) * 1.5)
    music.playTone(523, music.beat(BeatFraction.Half))
    music.playTone(554, music.beat(BeatFraction.Whole))
    music.playTone(622, music.beat(BeatFraction.Whole))
    music.playTone(698, music.beat(BeatFraction.Breve))
    music.rest(music.beat(BeatFraction.Whole))
}
function Vocal_L1 () {
    music.playTone(311, music.beat(BeatFraction.Whole))
    music.playTone(311, music.beat(BeatFraction.Whole))
    music.playTone(523, music.beat(BeatFraction.Whole))
    music.playTone(415, music.beat(BeatFraction.Whole) * 1.5)
    music.rest(music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Whole))
    music.playTone(415, music.beat(BeatFraction.Whole))
    music.playTone(415, music.beat(BeatFraction.Whole))
    music.playTone(622, music.beat(BeatFraction.Whole))
    music.playTone(523, music.beat(BeatFraction.Whole))
    music.playTone(415, music.beat(BeatFraction.Whole))
    music.playTone(392, music.beat(BeatFraction.Whole) * 1.5)
    music.playTone(415, music.beat(BeatFraction.Half))
    music.playTone(466, music.beat(BeatFraction.Double))
    music.rest(music.beat(BeatFraction.Whole))
}
function Vocal_L2 () {
    music.playTone(311, music.beat(BeatFraction.Whole))
    music.playTone(392, music.beat(BeatFraction.Whole))
    music.playTone(415, music.beat(BeatFraction.Whole))
    music.playTone(466, music.beat(BeatFraction.Double))
    music.rest(music.beat(BeatFraction.Whole))
    music.playTone(523, music.beat(BeatFraction.Whole))
    music.playTone(554, music.beat(BeatFraction.Whole))
    music.playTone(698, music.beat(BeatFraction.Whole))
    music.playTone(622, music.beat(BeatFraction.Whole) * 1.5)
    music.playTone(554, music.beat(BeatFraction.Half))
    music.playTone(523, music.beat(BeatFraction.Breve))
    music.rest(music.beat(BeatFraction.Whole))
}
function Vocal_L3 () {
    music.playTone(311, music.beat(BeatFraction.Whole))
    music.playTone(415, music.beat(BeatFraction.Whole))
    music.playTone(523, music.beat(BeatFraction.Whole))
    music.playTone(622, music.beat(BeatFraction.Double))
    music.rest(music.beat(BeatFraction.Whole))
    music.playTone(523, music.beat(BeatFraction.Whole))
    music.playTone(554, music.beat(BeatFraction.Whole) * 1.5)
    music.playTone(523, music.beat(BeatFraction.Half))
    music.playTone(554, music.beat(BeatFraction.Whole))
    music.playTone(622, music.beat(BeatFraction.Whole))
    music.playTone(698, music.beat(BeatFraction.Breve))
    music.rest(music.beat(BeatFraction.Whole))
}
function Vocal_L0 () {
    music.rest(music.beat(BeatFraction.Double))
    music.rest(music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Whole) * 1.5)
    music.rest(music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Whole))
}
radio.setGroup(1)
edubitRgbBit.setPixelColor(0, 0xff0000)
edubitRgbBit.setPixelColor(1, 0x0000ff)
edubitRgbBit.setPixelColor(2, 0xffff00)
edubitRgbBit.setPixelColor(3, 0xffffff)
basic.forever(function () {
    led.plotBarGraph(
    edubitSoundBit.readSoundSensor(),
    800
    )
})
